### ISSUE TITLE
Resistbot, but for State or Local Government

### ISSUE THREAD

**Issue by ardouglass** [sketch-city/project-ideas#103]
### The OG
https://resistbot.io/

### What it Is
Resistbot is pretty great and makes it easy to write to your representatives in the US House and Senate by texting "resist" to 50409. From there, it asks for your address so it can find your representatives. Then you tell it what you want to tell your representatives and it sends them a fax.

### What it Doesn't Do
It doesn't have any support for messaging state or local representatives, which arguably have a larger impact on our lives. They are rapidly expanding to add new features, but I don't know if this is something they'll do since it adds a different level of complexity in the amount of geodata and contact info they need to collect and maintain. **It also isn't open source, and that makes me sad.** 😢 

### Project Idea
Build an open source clone of Resistbot that anyone can spin up for any type of jurisdiction. This spreads out the cost of operation and also allows local individuals to be responsible for keeping the geodata and contact information up to date.

**Comment by zenjen777** [comment]
This is a super cool idea!!! 😀 Could def see lots of non-profits who lobby
for or against specific issues or bills could really use something like
this!

Jen Greer

On Apr 27, 2017 11:23 PM, "Andrew Douglass" <notifications@github.com>
wrote:

The OG

https://resistbot.io/
What it Is

Resistbot is pretty great and makes it easy to write to your
representatives in the US House and Senate by texting "resist" to 50409.
From there, it asks for your address so it can find your representatives.
Then you tell it what you want to tell your representatives and it sends
them a fax.
What it Doesn't Do

It doesn't have any support for messaging state or local representatives,
which arguably have a larger impact on our lives. They are rapidly
expanding to add new features, but I don't know if this is something
they'll do since it adds a different level of complexity in the amount of
geodata and contact info they need to collect and maintain. *It also isn't
open source, and that makes me sad.* 😢
Project Idea

Build an open source clone of Resistbot that anyone can spin up for any
type of jurisdiction. This spreads out the cost of operation and also
allows local individuals to be responsible for keeping the geodata and
contact information up to date.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sketch-city/project-ideas/issues/103>, or mute the
thread

**Comment by fileunderjeff** [comment]
I love this idea. Here is some spatial data that I know we have:

- National & State House and State Senate districts, along with current elected officials.
- Houston City Council districts
- Houston ISD districts
- Harris County precinct boundaries
- Civic club boundaries
- Superneighborhood boundaries

Some data that would be helpful to acquire or actually construct at the hackathon:

- Additional city boundaries, such as Bellaire, West U, Hunters Creek Village, Galena Park, etc. as well as council districts within those boundaries.
- Additional school district trustee districts, such as Alief, Humble, etc.

**Comment by nberlanga** [comment]
Is this an open source project? If so, how can one obtain the code?

**Comment by ardouglass** [comment]
The concept has expanded somewhat for the purpose of being a bit more general (ex.: submit 311 requests through chat, ask for stats about the city, etc.), however being a local replacement for resistbot is still the initial goal and the scope for the hackathon.

You can see the project at: https://github.com/sketch-city/civicbot.
Project communication occurs on the Sketch City Slack at the #civicbot channel.
