### ISSUE TITLE
Fair Housing Price Index

### ISSUE THREAD

**Issue by pthompso201** [sketch-city/project-ideas#134]
The simplest way to create fairness in housing cost is to give people a quick single fairness score for a given property. This can be done using the federal minimum wage ($7.25), the maximum recommend percentage of income that should be spent on housing (30%), and the minimum number of square feet that is considered humane for daily living (320). This means that a residence should cost $1.08 per square foot to have an ideal fairness index of 0. The fairness index of a property would be positive for less than $1.08 and negative for those above $1.08. From there, the power of the Free market and consumer demand will force landlords to be transparent in pricing and justify any price over the baseline.

The application build should be a straight forward scrape of property pricing from various real estate index with the score applied and projected on a map.

This is the first and easiest part of the equity triangle to address.

**Comment by circushaase** [comment]
Has there been any development on this? Is there a data set to analyze? I'd be interested in doing something like this for my capstone project in my bootcamp, but I'm not sure where to scrape the data or how to go about doing it. If anyone would like to give me some advice or mentorship, I'd appreciate it, and we could potentially produce something worthwhile!

**Comment by fileunderjeff** [comment]
@circushaase Hi Lara, I just saw this. HCAD has property tax data, which isn't the same as MLS (realtor) data, but it is a good start. You could mark up the HCAD assessment by 20-30% and get a good proxy for sales data. Please let me know if I can help you with this project.

**Comment by circushaase** [comment]
Hi Jeff,
I ended up deciding to go with a different data set for my project. I'm using the dataset published by the Texas Justice Initiative on deaths in police custody in Texas from 2005-2016. I could use some help with that. Specifically, right now I'm looking for some statistics to compare the data to. Texasjusticeinitiative.org compared the death rates to Texas population rates, but I would like to compare to population rates of all people in custody during that time, in order to control for the fact that people of minority ethnicities are disproportionately arrested, to see beyond that if it is also more deadly for people of certain ethnicities to be in custody.
These seem like tricky numbers to find, but if you have any recommendations, I a m definitely open to them.
Here's my project in its current status:
https://github.com/circushaase/Capstone2
