### ISSUE TITLE
Map of basketball deserts

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#21]
Piggyback on [this project](https://github.com/sketch-city/basketball-mapping) and help develop a comprehensive map of all the public basketball hoops in Houston.

**Comment by poprox** [comment]
Very interested in this idea.  If I can make it this weekend I would like to work on this project as I enjoy playing basketball.

Think a crowdsource geoenabled app may be the best approach to collecting the data and then showing a map that has all of the various data sets easily understood such as vacant land, existing parks, existing centers with basketball locations, etc.

**Comment by poprox** [comment]
here is a quick map I put together with the a few live connections to some source data - these are live connections to City of Houston and Harris County data layers

Need to think through how to add other basketball specific data and property info, but could be used as a base to build upon

http://arcg.is/1NqPE8u

**Comment by fileunderjeff** [comment]
@poprox this is awesome!! i assembled some source datasets here: https://github.com/sketch-city/basketball-mapping/tree/master/source%20data too -- not sure if that's useful at this point. I'm excited to dig in!

**Comment by poprox** [comment]
@fileunderjeff yes I saw those - I'm not super familiar with GitHub yet - but in the map I connected to the live service feeds from City of Houston & Harris County - this is nice because if they make changes to the data the apps will automatically update

here are the links to the service URLs if anyone is interested:
Community Centers - http://mycity.houstontx.gov/arcgisweb/rest/services/PD/Neighborhood_Services_wm/MapServer/8
After School Programs - http://mycity.houstontx.gov/arcgisweb/rest/services/PD/Neighborhood_Services_wm/MapServer/6
Schools - http://mycity.houstontx.gov/arcgisweb/rest/services/PD/Neighborhood_Services_wm/MapServer/0
City of Houston Parks - http://mycity.houstontx.gov/arcgisweb/rest/services/PD/Neighborhood_Services_wm/MapServer/11
Harris County Parks - http://www.gis.hctx.net/arcgis/rest/services/repository/PID_Parks/MapServer/0

**Comment by fileunderjeff** [comment]
@poprox agreed!
