### ISSUE TITLE
Adopt a storm drain!

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#81]
In San Francisco, there is a great program to [adopt a storm drain](https://adoptadrain.sfwater.org). Here in Houston, there is a lot of interest in doing something similar.

This project has several facets:

- Build the technical platform
- Organize inlet data from PWE's map service
- Determine pilot neighborhoods -- preferably older neighborhoods with B-size inlets
- Develop a marketing campaign to spread the word on Nextdoor and through civic associations

This project has the support of the Mayor's office. Please let me know if you're interested in contributing!

**Comment by rlgreen91** [comment]
This looks like a fun one!

**Comment by BenjaminFlores** [comment]
Hi, 

For the technical platform can I suggest using firebase and geo firebase? I've been using it for a few months and can do the work really smooth. It works with javascript and json files.

https://github.com/firebase/geofire-js
https://firebase.google.com/

Let me try to build a pilot to see if it will work.

**Comment by poprox** [comment]
Esri has a opensource solution that could work with the data and systems that the City currently uses to maintain the location and asset information of the inlets

http://solutions.arcgis.com/local-government/help/adopta/

It would be fairly straightforward to connect to the City's existing system and work with their team to enable this project to work with their data stream

**Comment by fileunderjeff** [comment]
It is especially cool that the module is free, and can notify all the people involved of an upcoming storm. I'd suggest we explore that module first, along with any Code for America open source repos from a few years back for additional ideas, if needed.

**Comment by BenjaminFlores** [comment]
Hey @poprox @fileunderjeff , still interested in trying this project? maybe we can share ideas starting next week so we can have base grounds before the hackathon. I know @fileunderjeff you will be helping during the event, me too, but I think we can still work on this... let me know...

**Comment by fileunderjeff** [comment]
@BenjaminFlores i am definitely interested in helping on this project. looking forward to discussing more next week.

**Comment by LawExplorer** [comment]
With regard to marketing, I read an [article](https://www.thestar.com/news/innovation/2017/05/11/so-youd-like-to-quit-smoking-why-not-collect-points-in-the-process.html) this morning about the impact of a B Corp called "[Carrot Insights](http://www.carrotinsights.com/en/home/)" in Toronto, Canada.  It offers an app that rewards points to encourage constructive behavior.

**Comment by BenjaminFlores** [comment]
@fileunderjeff awesome... are you guys available this next Tuesday afternoon?

**Comment by buck** [comment]
Hi,
I was talking with Jesse Biroscak, Code for America brigade leader in San Francisco, about how few civic apps I can find that ever make a jump to another city.  This was in March 2016, and he pointed me to Boston's Adopt-a-Hydrant Rails code, and SF's cloning of it to storm drains.  Of course, my ears perked up at storm drains in Houston, and I put up this sample site on March 18, 2016, which turned out to be just a few weeks before our spring flooding event.

[]http://ancient-depths-27071.herokuapp.com/

I took about 90 minutes and walked around to all the storm drains around my house and took a GPS reading on my phone, so I had a set of 71 drains to seed the site with.  If you play with it some, it is pretty nice as far as basic function.  It has an odd feature of drawing the drains one at a time only around the cursor.  It also is a disaster on mobile, as the keyboard keeps popping up over the map, at least on my Android device.  That is pretty easy to fix for someone that designs responsive web sites.

The real issue is I'm not sure this is a problem.  Every single drain around my house was clean as a whistle, with the curved metal running under the curb.  There are probably some drains that clog, but most don't seem to need any care.  The feature that will email drain adoptors as a rain event approaches would certainly be nice, and easy to add to this shared codebase.  I went to the Harris County Flood Control District office back then, and they told me that individual cities hold the lat/long data for their maintenance activities.  At a Rice Design Alliance seminar a couple of months ago on Houston flooding, a Harris County Flood Control engineer was telling me how actually, each utility district or even subdivision holds control over their storm drains, ugh!  That is several hundred entities in Harris County.

Jesse was telling me how the slope in San Francisco leads to debris easily clogging the drains and can easily flood a street.  I haven't tracked down a straight answer from anyone in the know in flood control about where our storm drains are actually clogging, when , etc., etc.  We've all seen the TV reports of heroic neighbors clearing the clogged drain near their neighborhood and saving it from flooding.  Just not sure that happens a lot for normal drainage in our area.

This is the RDA civic forum I attended on March 8:
http://us5.campaign-archive1.com/?u=8d0d70665cc30c192fca3b06c&id=3e205f76a7&e=e4ab0a6157

Alisa Max, PE, Harris County Watershed Protection Group Manager

I chatted with Alisa Max after she have a very interesting talk about designing for flood control, and she gave me some names but I haven't followed up with anyone since.

I also see zero need to tie this to a commercial product like ArcGIS.  All it needs is lat/long for all drains, and Google Maps does the rest.  Of course, getting anyone to use it is the real challenge in this.

Cheers,
Lester
buck@compact.com
832-475-8085

**Comment by fileunderjeff** [comment]
@buck i spoke with folks at the city, and they confirmed the problem. it's mostly a concern in areas with heavy tree cover, so we are getting the storm drain info for selected areas. ESRI's product is also good because it has a built in communications module, and it's something the city could take over after it's configured, since they already have the licenses and competencies.

**Comment by BenjaminFlores** [comment]
If you guys don't mind, I just created a slack channel "adopt-storm-drain" in the sketch city so we can communicate better and invite more people if interested. @buck I don't see your handle on the sketch city channel, please if you can share it so I can add you on.

Also, I agree with using the option of ESRI. Does anyone have any space or sandbox server we can play with? or if you don't mind, I have an AWS sandbox (IIS) that we can use for the project.

**Comment by poprox** [comment]
@BenjaminFlores I added some info on the Slack - FYI - unfortunately I have a family situation and won't be able to attend the Hackathon on Saturday or the meetup on 5/16 - but hopefully I can help out from a distance and will try to make it Sunday of the Hackathon.

**Comment by BenjaminFlores** [comment]
@poprox no problem, we can be working remotely... we will be keeping you posted and hopefully see you Sunday morning
