### ISSUE TITLE
Do You Really Want to Eat Here?

### ISSUE THREAD

**Issue by rlgreen91** [sketch-city/project-ideas#87]
An app that will, given a restaurant location, will tell you the results of the most recent inspections.

Can be based on this dataset: https://data.world/houston/houston-food-inspections

Possible integration with Google Home/Search/Maps

Would be best to note overall trends (e.g., steadily improving grades, overall high grades, etc.).

**Comment by fileunderjeff** [comment]
It looks like these records need to be geocoded. Across the years 2011-2015, there are 200,000+ records for geocoding. We should consider the costs and/or the time required for geocoding this information. We could also request that the city geocode and republish these datasets.

**Comment by rlgreen91** [comment]
@fileunderjeff - Is it worth considering making the geocoding a separate issue?  Something to either teach people how to geocode, or to request a dataset, and overall what it means to provide a "good" dataset?  I've never actually geocoded something, so I'll understand if it's something that doesn't make sense as a project for someone other than the source of the data.

**Comment by fileunderjeff** [comment]
@rlgreen91 we can do that. Without the geocoding, the user would have to pick from a list of restaurants rather than browse on a map. That might work for a prototype!

Geocoding is quite simple, and there are lots of ways to do it. For small datasets, I use the Google Maps API that is built into `ggmap` for R. You send it a string and it returns a lat/lon if there is a match.

For larger jobs, you can upload a spreadsheet to a service like Geocod.io and it will return batch results. 

It requires data processing, so it can take a few hours for a large job. There are also free limits for different services, usually 1,500-2,500 records a day.

**Comment by rlgreen91** [comment]
Sounds like a good project for the hackathon then - to create some type of script that will get datasets that need to be geocoded and do that process.  Not the sexiest thing, but well, not everything about programming is super fun, that's for sure.

**Comment by antonywu** [comment]
I actually think that if we focus on most recent inspection results, it will be much more helpful. 

Restaurants may change ownership, so old inspection results may not reflect the new management in place. Furthermore, on /r/houston, it seems the consensus is that most restaurant have a violation or two, but it does not deter people from going to eat there. Case to the point. House of Pies. I literally live right across from that place, and I have seen them on violations quite a few times on Chronicles. Still, people go there to eat. They do have good pies though (So much so that the business idea of Compaq started out at House of Pies.)

**Comment by meowmeowcomputers** [comment]
I'm interested in joining this team! I'm learning the gmap API, and am moderately strong with databases. Maybe datapoints on a map, color coded by how recent violations occur?

**Comment by meowmeowcomputers** [comment]
I've inserted the 2016 data in to Google Fusion Tables, and looks like it's batch Geolocating for me. I'll post the results when it finishes.
